build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - apk add git
    - git clone -b stable https://git.pleroma.social/pleroma/pleroma
    - VERSION=$(git describe --tags --abbrev=0)
    - rm -r -f pleroma
  script:
    - docker build --pull -t "$VERSION" .
    - docker push "$VERSION"

include:
  - template: Container-Scanning.gitlab-ci.yml
