build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - apk add git
    - git clone -b stable https://git.pleroma.social/pleroma/pleroma.git
    - cd pleroma
    - VERSION=$(git describe --tags --abbrev=0)
    - cd ..
    - rm -r -f pleroma
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:$VERSION .
    - docker push $CI_REGISTRY_IMAGE:$VERSION

include:
  - template: Container-Scanning.gitlab-ci.yml
