build:
  # Official docker image.
  image: quay.io/podman/stable
  stage: build
  before_script:
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - dnf install -y git-all
    - git clone -b stable https://akkoma.dev/AkkomaGang/akkoma.git
    - cd akkoma
    - VERSION=$(git describe --tags --abbrev=0)
    - cd ..
    - rm -r -f akkoma
  script:
    - podman build --pull -t $CI_REGISTRY_IMAGE:$VERSION -t $CI_REGISTRY_IMAGE:latest .
    - podman push $CI_REGISTRY_IMAGE:$VERSION
    - podman push $CI_REGISTRY_IMAGE:latest

include:
  - template: Security/Container-Scanning.gitlab-ci.yml

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:latest

container_scanning:
  variables:
    GIT_STRATEGY: fetch
    DOCKERFILE_PATH: "./Dockerfile"
